<?php
/**
 * Build a single customer record. Each customer owns a completely isolated
 * set of financial sub-records (wallet, orders, transactions, deposits,
 * withdrawals, notifications, tickets, bank, admin notes, activity). This is
 * what makes multi-tenancy real: there is no longer one shared "global" wallet
 * that every registered user overwrites.
 */
function build_customer(array $profile, array $wallet, array $orders, array $transactions, array $deposits, array $withdrawals, array $notifications, array $tickets, array $bank, array $adminNotes): array
{
    return array_merge($profile, [
        'wallet' => $wallet,
        'orders' => $orders,
        'transactions' => $transactions,
        'deposits' => $deposits,
        'withdrawals' => $withdrawals,
        'notifications' => $notifications,
        'tickets' => $tickets,
        'bank' => $bank,
        'claimed_rewards' => [],
        'activities' => [],
        'admin_notes' => $adminNotes,
    ]);
}

function seed_platform_data(): array
{
    $demoWallet = [
        'available' => 300.00,
        'locked' => 0.00,
        'bonus' => 0.00,
        'referral' => 0.00,
        'investment' => 150.00,
        'pending' => 0.00,
        'withdrawable' => 300.00,
        'frozen' => false,
    ];

    $demoOrders = [
        [
            'id' => 'ORD-2401',
            'plan' => 'Apple Inc.',
            'symbol' => 'AAPL',
            'amount' => 150.00,
            'profit' => 2.70,
            'progress' => 40,
            'status' => 'Active',
            'user_id' => 1221,
            'purchase_date' => date('Y-m-d', strtotime('-12 days')),
            'completion_date' => date('Y-m-d', strtotime('+18 days')),
            'expected' => 156.75,
            'net_profit' => 6.75,
            'image' => 'aapl-logo',
        ],
    ];

    $demoTransactions = [
        ['id' => 'TXN-1001', 'type' => 'Investment Purchase', 'category' => 'Debit', 'amount' => 150.00, 'old' => 450.00, 'new' => 300.00, 'status' => 'Completed', 'date' => date('Y-m-d H:i', strtotime('-12 days')), 'description' => 'Apple Inc. purchase'],
        ['id' => 'TXN-1000', 'type' => 'Deposit', 'category' => 'Credit', 'amount' => 450.00, 'old' => 0.00, 'new' => 450.00, 'status' => 'Approved', 'date' => date('Y-m-d H:i', strtotime('-13 days')), 'description' => 'USDT TRC20 recharge'],
    ];

    $demoDeposits = [
        ['id' => 'DEP-9001', 'user_id' => 1221, 'amount' => 450.00, 'method' => 'USDT(TRC20)', 'reference' => 'TRC-DEMO-9001', 'status' => 'Approved', 'date' => date('Y-m-d H:i', strtotime('-13 days'))],
    ];

    $demoNotifications = [
        ['title' => 'Investment active', 'message' => 'Apple Inc. is generating daily earnings.', 'type' => 'Investment', 'read' => false, 'date' => date('Y-m-d H:i')],
        ['title' => 'Deposit approved', 'message' => 'Your USDT(TRC20) recharge was approved.', 'type' => 'Financial', 'read' => true, 'date' => date('Y-m-d H:i', strtotime('-13 days'))],
    ];

    $demoTickets = [
        ['id' => 'SUP-2101', 'subject' => 'Withdrawal verification', 'status' => 'Open', 'priority' => 'Normal', 'updated' => date('Y-m-d H:i', strtotime('-2 days'))],
    ];

    $demoBank = [
        'holder' => '',
        'account' => '',
        'method' => '',
    ];

    $demoAdminNotes = [
        ['user_id' => 1221, 'note' => 'Account reviewed during onboarding.', 'admin' => 'Platform Admin', 'date' => date('Y-m-d H:i:s', strtotime('-7 days'))],
    ];

    $apex = build_customer([
        'id' => 1221,
        'username' => 'Apex',
        'full_name' => 'Apex Investor',
        'email' => 'apex@example.com',
        'phone' => '7043340662',
        'country' => 'Nigeria',
        'city' => 'Lagos',
        'membership' => 'Pro Account',
        'status' => 'Active',
        'referral_code' => 'zn911yr229',
        'sponsor' => 'Nivaro Partner Desk',
        'last_login' => date('Y-m-d H:i:s'),
    ], $demoWallet, $demoOrders, $demoTransactions, $demoDeposits, [], $demoNotifications, $demoTickets, $demoBank, $demoAdminNotes);

    // A second seeded customer proves the data is isolated per-account.
    $novaWallet = [
        'available' => 120.00,
        'locked' => 0.00,
        'bonus' => 0.00,
        'referral' => 0.00,
        'investment' => 80.00,
        'pending' => 0.00,
        'withdrawable' => 120.00,
        'frozen' => false,
    ];

    $nova = build_customer([
        'id' => 1222,
        'username' => 'Nova',
        'full_name' => 'Nova Trader',
        'email' => 'nova@example.com',
        'phone' => '8012233445',
        'country' => 'Ghana',
        'city' => 'Accra',
        'membership' => 'Starter Account',
        'status' => 'Active',
        'referral_code' => 'nv552yk001',
        'sponsor' => 'Nivaro Partner Desk',
        'last_login' => date('Y-m-d H:i:s'),
    ], $novaWallet, [], [], [], [], [], [], $demoBank, []);

    return [
        'customers' => [
            1221 => $apex,
            1222 => $nova,
        ],
        'plans' => seed_investment_plans(),
        'referral_levels' => [
            ['level' => 1, 'name' => 'Direct Referrals', 'size' => 0, 'earn' => 0.00, 'rate' => 11],
            ['level' => 2, 'name' => 'Indirect Referrals', 'size' => 0, 'earn' => 0.00, 'rate' => 2],
            ['level' => 3, 'name' => 'Sub-Indirect Referrals', 'size' => 0, 'earn' => 0.00, 'rate' => 1],
        ],
        'rewards_catalog' => [
            ['code' => 'WELCOME50', 'title' => 'Welcome Bonus', 'amount' => 5.00, 'status' => 'Available', 'expires' => date('Y-m-d', strtotime('+30 days'))],
            ['code' => 'TEAMBOOST', 'title' => 'Team Growth Bonus', 'amount' => 15.00, 'status' => 'Locked', 'expires' => date('Y-m-d', strtotime('+45 days'))],
        ],
        'notifications' => [],
        'tickets' => [],
        'activities' => [],
        'admin_logs' => [],
        'settings' => [
            'site_name' => 'Nivaro Capital',
            'registration' => 'Enabled',
            'maintenance' => 'Disabled',
            'min_deposit' => 10,
            'max_deposit' => 5000,
            'min_withdrawal' => 10,
            'fee' => 1.5,
        ],
        'crypto_wallets' => default_crypto_wallets(),
        'metrics' => [],
    ];
}

function seed_investment_plans(): array
{
    return [
        [
            'id' => 1,
            'name' => 'Apple Inc.',
            'symbol' => 'AAPL',
            'category' => 'Stock',
            'description' => 'Apple is among the largest companies in the world, with a broad portfolio of hardware and software products targeted at consumers and businesses. Apple\'s iPhone accounts for the majority of the firm\'s sales, and Apple\'s other products, such as the Mac, iPad, and Watch, are designed around the iPhone as the focal point of an expansive software ecosystem. Apple has progressively worked to add new applications, such as streaming video, subscription bundles, and augmented reality. The firm designs its own software and semiconductors and works with subcontractors such as Foxconn and TSMC to build its products and chips. Slightly less than half of Apple\'s sales come directly through its flagship stores, with the majority coming indirectly through partnerships and distribution.',
            'image' => 'aapl-logo',
            'banner_image' => 'aapl-banner',
            'ai_summary' => 'Apple Inc. is currently experiencing a modest decline in daily and weekly trends, despite a strong upward trajectory over the past month and year. As a mega-cap company, it continues to hold a significant position in the market with a diverse product portfolio.',
            'key_points' => "Daily and weekly trends show modest declines, while monthly and yearly performance remains strong.\nThe company's extensive range of products, particularly the iPhone, drives the majority of sales.\nApple maintains a small dividend, reflecting its commitment to returning value to shareholders.",
            'risk_level' => 'Low',
            'price' => 189.50,
            'min' => 50.00,
            'max' => 10000.00,
            'daily' => 0.28,
            'daily_return' => 0.15,
            'monthly_return' => 4.50,
            'roi' => 104.50,
            'duration' => 30,
            'lock_period' => 15,
            'status' => 'Open',
            'featured' => true,
            'is_trending' => true,
            'is_beginner_friendly' => true,
            'has_dividend' => true,
            'is_popular' => true,
            'market_status' => 'Open',
            'sort_order' => 10,
            'market_cap' => '4.62T',
            'open' => 317.46,
            'high' => 328.52,
            'low' => 317.4,
            'dividend_yield' => 0.33
        ],
        [
            'id' => 2,
            'name' => 'Bitcoin',
            'symbol' => 'BTC',
            'category' => 'Cryptocurrency',
            'description' => 'The first and largest decentralized digital asset, serving as digital gold and a store of value.',
            'image' => 'btc-logo',
            'banner_image' => 'btc-banner',
            'ai_summary' => 'Cryptocurrency markets are showing high momentum. BTC has strong support at $60k. Our AI forecasts a potential 12.5% return for the current lock period, with elevated volatility.',
            'key_points' => "High institutional ETF inflows\nHalving supply shock dynamics\nGlobal liquid macro hedge",
            'risk_level' => 'High',
            'price' => 64250.00,
            'min' => 100.00,
            'max' => 50000.00,
            'daily' => 2.67,
            'daily_return' => 0.42,
            'monthly_return' => 12.50,
            'roi' => 112.50,
            'duration' => 30,
            'lock_period' => 30,
            'status' => 'Open',
            'featured' => true,
            'is_trending' => true,
            'is_beginner_friendly' => false,
            'has_dividend' => false,
            'is_popular' => true,
            'market_status' => 'Open',
            'sort_order' => 20,
            'market_cap' => '1.27T',
            'open' => 64100.00,
            'high' => 65200.00,
            'low' => 63800.00
        ],
        [
            'id' => 3,
            'name' => 'NVIDIA Corporation',
            'symbol' => 'NVDA',
            'category' => 'Stock',
            'description' => 'Pioneer of GPU-accelerated computing, dominating AI chip manufacturing and enterprise hardware.',
            'image' => 'nvda-logo',
            'banner_image' => 'nvda-banner',
            'ai_summary' => 'AI infrastructure spending remains at historic highs. NVDA is the primary beneficiary. Expect high volatility but high returns, projected at 18.0% over the next 45 days.',
            'key_points' => "Near-monopoly in AI chips\nUnprecedented data center demand\nStrong cash flow generation",
            'risk_level' => 'Medium',
            'price' => 127.40,
            'min' => 150.00,
            'max' => 25000.00,
            'daily' => 0.51,
            'daily_return' => 0.40,
            'monthly_return' => 12.00,
            'roi' => 118.00,
            'duration' => 45,
            'lock_period' => 20,
            'status' => 'Open',
            'featured' => true,
            'is_trending' => false,
            'is_beginner_friendly' => false,
            'has_dividend' => true,
            'is_popular' => true,
            'market_status' => 'Open',
            'sort_order' => 30,
            'market_cap' => '3.12T',
            'open' => 126.80,
            'high' => 129.10,
            'low' => 125.40
        ],
        [
            'id' => 4,
            'name' => 'S&P 500 ETF',
            'symbol' => 'SPY',
            'category' => 'ETF',
            'description' => 'Exchange Traded Fund tracking the 500 largest US publicly traded companies by market capitalization.',
            'image' => 'spy-logo',
            'banner_image' => 'spy-banner',
            'ai_summary' => 'Broad-market exposure through SPY represents the lowest risk profile. AI recommends SPY as a foundational portfolio holding with an expected 2.8% monthly return.',
            'key_points' => "Instant diversification\nTracks the health of the US economy\nHighly liquid options chain",
            'risk_level' => 'Low',
            'price' => 542.10,
            'min' => 20.00,
            'max' => 50000.00,
            'daily' => 0.05,
            'daily_return' => 0.09,
            'monthly_return' => 2.80,
            'roi' => 102.80,
            'duration' => 30,
            'lock_period' => 5,
            'status' => 'Open',
            'featured' => false,
            'is_trending' => false,
            'is_beginner_friendly' => true,
            'has_dividend' => true,
            'is_popular' => false,
            'market_status' => 'Open',
            'sort_order' => 40,
            'market_cap' => '542.10B',
            'open' => 540.20,
            'high' => 544.80,
            'low' => 539.10
        ],
        [
            'id' => 5,
            'name' => 'SpaceX',
            'symbol' => 'SPCX',
            'category' => 'Stock',
            'description' => 'SpaceX, the Space Exploration Technologies Corporation designs, manufactures, and operates a family of reusable rockets to launch various payloads into Earth orbit for government and commercial customers. Starting in 2019, the company began launching a constellation of its own communication satellites to provide mobile broadband and wireless services under the Starlink brand. In early 2026, the company acquired xAI from its founder, Elon Musk, which operates a large language artificial intelligence model named Grok, a gigawatt-scale data center called Colossus, and the social media network X.',
            'image' => 'spcx-logo',
            'banner_image' => 'spcx-banner',
            'ai_summary' => 'Space Exploration Technologies Corp. Class A is currently experiencing significant downward pressure across multiple time frames, indicating a challenging market environment. Despite its strong position as a mega cap company and a consistent dividend payer, recent trends suggest investor sentiment is cautious.',
            'key_points' => "The stock has seen a strong decline in daily, weekly, and monthly trends.\nYearly performance reflects a substantial downturn.\nThe company maintains a small dividend, which may provide some support to investors.",
            'risk_level' => 'Medium',
            'price' => 134.28,
            'min' => 50.00,
            'max' => 10000.00,
            'daily' => 0.20,
            'daily_return' => 0.12,
            'monthly_return' => 3.60,
            'roi' => 103.60,
            'duration' => 30,
            'lock_period' => 15,
            'status' => 'Open',
            'featured' => false,
            'is_trending' => false,
            'is_beginner_friendly' => false,
            'has_dividend' => true,
            'is_popular' => false,
            'market_status' => 'Open',
            'sort_order' => 50,
            'market_cap' => '1.79T',
            'open' => 137.45,
            'high' => 139.33,
            'low' => 132.25,
            'dividend_yield' => 0.36
        ],
        [
            'id' => 6,
            'name' => 'Tesla',
            'symbol' => 'TSLA',
            'category' => 'Stock',
            'description' => 'Tesla is a vertically integrated battery electric vehicle automaker and developer of real-world artificial intelligence software, which includes autonomous driving and humanoid robots. The company has multiple vehicles in its fleet, which include a midsize sedan and crossover SUV in the entry-level luxury category, a luxury light truck, and a semitruck. Tesla also runs a robotaxi service in four US metropolitan areas. Global deliveries in 2025 were nearly 1.64 million vehicles. Additionally, the company sells batteries for stationary storage for residential and commercial properties, including utilities, solar panels, and solar roofs for energy generation. Tesla also owns a fast-charging network and a US auto insurance business.',
            'image' => 'tsla-logo',
            'banner_image' => 'tsla-banner',
            'ai_summary' => 'Tesla\'s stock is currently experiencing a strong decline on the daily trend, despite a slight increase over the past week. While the monthly performance shows a significant drop, the yearly trend remains robust with substantial growth. Overall, the stock is positioned at a very high price level.',
            'key_points' => "Daily stock performance indicates a strong downward movement.\nWeekly trends show a slight recovery after recent declines.\nYearly performance highlights significant growth despite recent volatility.",
            'risk_level' => 'High',
            'price' => 394.83,
            'min' => 50.00,
            'max' => 10000.00,
            'daily' => 0.45,
            'daily_return' => 0.25,
            'monthly_return' => 7.50,
            'roi' => 107.50,
            'duration' => 30,
            'lock_period' => 15,
            'status' => 'Open',
            'featured' => false,
            'is_trending' => false,
            'is_beginner_friendly' => false,
            'has_dividend' => false,
            'is_popular' => false,
            'market_status' => 'Open',
            'sort_order' => 60,
            'market_cap' => '1.49T',
            'open' => 400.5,
            'high' => 406.58,
            'low' => 390.71
        ],
        [
            'id' => 7,
            'name' => 'Shopify',
            'symbol' => 'SHOP',
            'category' => 'Stock',
            'description' => 'Shopify offers an e-commerce platform primarily on small and medium-size businesses. The firm has two segments. The subscription solutions segment allows Shopify merchants to conduct e-commerce on a variety of platforms, including the company\'s website, physical stores, pop-up stores, kiosks, social networks (Facebook), and Amazon. The merchant solutions segment offers add-on products for the platform that facilitate e-commerce and include Shopify Payments, Shopify Shipping, and Shopify Capital.',
            'image' => 'shop-logo',
            'banner_image' => 'shop-banner',
            'ai_summary' => '',
            'key_points' => '',
            'risk_level' => 'Medium',
            'price' => 124.71,
            'min' => 50.00,
            'max' => 10000.00,
            'daily' => 0.28,
            'daily_return' => 0.16,
            'monthly_return' => 4.80,
            'roi' => 104.80,
            'duration' => 30,
            'lock_period' => 15,
            'status' => 'Open',
            'featured' => false,
            'is_trending' => false,
            'is_beginner_friendly' => false,
            'has_dividend' => false,
            'is_popular' => false,
            'market_status' => 'Open',
            'sort_order' => 70,
            'market_cap' => '163.09B',
            'open' => 126.7,
            'high' => 127.22,
            'low' => 120.91
        ],
        [
            'id' => 8,
            'name' => 'Coinbase',
            'symbol' => 'COIN',
            'category' => 'Stock',
            'description' => 'Founded in 2012, Coinbase is the leading cryptocurrency exchange platform in the United States. The company intends to be the safe and regulation-compliant point of entry for retail investors and institutions into the cryptocurrency economy. Users can establish an account directly with the firm, instead of using an intermediary, and many choose to allow Coinbase to act as a custodian for their cryptocurrency, giving the company breadth beyond that of a traditional financial exchange. While the company still generates the majority of its revenue from transaction fees charged to its retail customers, Coinbase uses internal investment and acquisitions to expand into adjacent businesses, such as prime brokerage and data analytics.',
            'image' => 'coin-logo',
            'banner_image' => 'coin-banner',
            'ai_summary' => 'Coinbase Global, Inc. Class A has experienced a mixed performance recently, with a slight decline in daily trading despite a strong weekly increase. However, the stock has faced significant downward pressure over the longer term, particularly on a monthly and yearly basis.',
            'key_points' => "Daily trading shows a slight decrease while weekly performance is strong.\nMonthly and yearly trends indicate substantial declines.\nAs a large-cap company, Coinbase remains a key player in the cryptocurrency exchange market.",
            'risk_level' => 'High',
            'price' => 165.90,
            'min' => 50.00,
            'max' => 10000.00,
            'daily' => 0.40,
            'daily_return' => 0.22,
            'monthly_return' => 6.50,
            'roi' => 106.50,
            'duration' => 30,
            'lock_period' => 15,
            'status' => 'Open',
            'featured' => false,
            'is_trending' => false,
            'is_beginner_friendly' => false,
            'has_dividend' => false,
            'is_popular' => false,
            'market_status' => 'Open',
            'sort_order' => 80,
            'market_cap' => '42.55B',
            'open' => 165.59,
            'high' => 168.41,
            'low' => 160.63
        ],
        [
            'id' => 9,
            'name' => 'Invesco',
            'symbol' => 'QQQ',
            'category' => 'ETF',
            'description' => '',
            'image' => 'qqq-logo',
            'banner_image' => 'qqq-banner',
            'ai_summary' => 'Invesco QQQ Trust is currently experiencing a modest daily increase, following a strong weekly performance. However, the stock has faced significant declines over the past month, despite a robust yearly gain.',
            'key_points' => "Current price level is very high, indicating strong investor interest.\nDaily trend shows a modest upward movement, suggesting short-term positivity.\nWeekly performance is strong, contrasting with a notable decline over the past month.\nThe stock pays a small dividend, providing some income for investors.",
            'risk_level' => 'Medium',
            'price' => 719.71,
            'min' => 20.00,
            'max' => 50000.00,
            'daily' => 0.30,
            'daily_return' => 0.14,
            'monthly_return' => 4.20,
            'roi' => 104.20,
            'duration' => 30,
            'lock_period' => 5,
            'status' => 'Open',
            'featured' => false,
            'is_trending' => false,
            'is_beginner_friendly' => false,
            'has_dividend' => true,
            'is_popular' => false,
            'market_status' => 'Open',
            'sort_order' => 90,
            'open' => 724.16,
            'high' => 724.31,
            'low' => 710.27,
            'dividend_yield' => 0.45
        ],
    ];
}

/**
 * Canonical list of supported cryptocurrencies and their deposit addresses.
 * The "address" values are demo placeholders; administrators can rotate them
 * at any time from the admin Payment Settings screen, and the change is the
 * single source of truth consumed by the deposit workflow.
 */
function default_crypto_wallets(): array
{
    return [
        'BTC' => [
            'symbol' => 'BTC',
            'name' => 'Bitcoin',
            'network' => 'Bitcoin',
            'icon' => '₿',
            'address' => 'bc1qexamplebtcwalletaddressfornivarocapital000',
            'description' => 'Send only Bitcoin (BTC) over the native Bitcoin network.',
            'min' => 0.0005,
        ],
        'USDT' => [
            'symbol' => 'USDT',
            'name' => 'Tether',
            'network' => 'TRC20',
            'icon' => '₮',
            'address' => 'TQn9Y2khEsLJW1j9xkfqP7U7bL3nV6mZqX',
            'description' => 'Send only Tether (USDT) over the TRC20 (Tron) network.',
            'min' => 10.00,
        ],
        'USDC' => [
            'symbol' => 'USDC',
            'name' => 'USD Coin',
            'network' => 'ERC20',
            'icon' => '$',
            'address' => '0x4E8337d43c741C4e8613bE6f260C4D9Cff1d7E2B',
            'description' => 'Send only USD Coin (USDC) over the ERC20 (Ethereum) network.',
            'min' => 10.00,
        ],
    ];
}
